# Generated by Django 3.1.1 on 2021-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
