# Generated by Django 3.1.1 on 2021-06-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_formteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormTeacher',
        ),
    ]
