# Generated by Django 3.1.1 on 2021-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_formteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='class_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='highest_in_class',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='lowest_in_class',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
